### ISSUE TITLE
ios 6 crush

### ISSUE THREAD

**Issue by pilosof** [appcelerator-modules/ti.worker#6]
works fine on ios<6

on 6 - SDK 2.1.3
KrollBridge.mm line 598 

 [self evalFile:[url path] callback:self selector:@selector(booted)]; 

url is nil: (supposed ti be the wrapped javascript) ...

**Comment by hansemannn** [comment]
Tested with 6.0.0.GA and iOS 10, works fine. Use #15 for newer SDK versions please. Thx!
